#!/usr/bin/env python3
"""gen_font.py - emit fly/font57.h: the miner's 5x7 mixed-case font plus
the punctuation the FLY copy needs (the wallet font left 32..47 blank).

Run from fly/:  python3 gen_font.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "viz"))
import font5x7w as m  # noqa: E402

GW, GH = m.GW, m.GH
F = dict(m._F)

# Baseline is row 5; caps/digits use rows 0-5; descenders on row 6.
PUNCT = {
    ',': ["00000", "00000", "00000", "00000", "00110", "00100", "01000"],
    '.': ["00000", "00000", "00000", "00000", "00110", "00110", "00000"],
    "'": ["00110", "00100", "01000", "00000", "00000", "00000", "00000"],
    ':': ["00000", "00110", "00110", "00000", "00110", "00110", "00000"],
    ';': ["00000", "00110", "00110", "00000", "00110", "00100", "01000"],
    '-': ["00000", "00000", "00000", "11111", "00000", "00000", "00000"],
    '/': ["00001", "00010", "00100", "01000", "10000", "00000", "00000"],
    '(': ["00100", "01000", "01000", "01000", "01000", "00100", "00000"],
    ')': ["00100", "00010", "00010", "00010", "00010", "00100", "00000"],
    '[': ["01110", "01000", "01000", "01000", "01000", "01110", "00000"],
    ']': ["01110", "00010", "00010", "00010", "00010", "01110", "00000"],
    '#': ["01010", "11111", "01010", "01010", "11111", "01010", "00000"],
    '%': ["11001", "11010", "00100", "01000", "01011", "10011", "00000"],
    '!': ["00100", "00100", "00100", "00100", "00000", "00100", "00000"],
    '?': ["01110", "10001", "00010", "00100", "00000", "00100", "00000"],
    '+': ["00000", "00100", "00100", "11111", "00100", "00100", "00000"],
    '=': ["00000", "00000", "11111", "00000", "11111", "00000", "00000"],
    '"': ["01010", "01010", "00000", "00000", "00000", "00000", "00000"],
    '&': ["01000", "10100", "01000", "10101", "10010", "01101", "00000"],
    '*': ["00000", "10101", "01110", "11111", "01110", "10101", "00000"],
    '_': ["00000", "00000", "00000", "00000", "00000", "00000", "11111"],
    '<': ["00010", "00100", "01000", "00100", "00010", "00000", "00000"],
    '>': ["01000", "00100", "00010", "00100", "01000", "00000", "00000"],
    '@': ["01110", "10001", "10111", "10101", "10111", "10000", "01110"],
    'x': ["00000", "00000", "10001", "01010", "00100", "01010", "10001"],
}
for k, v in PUNCT.items():
    if k not in F or not any('1' in r for r in F[k]):
        F[k] = v

LO, HI = 32, 122
rows = []
missing = []
for code in range(LO, HI + 1):
    ch = chr(code)
    bmp = F.get(ch)
    if bmp is None or not any('1' in r for r in bmp):
        bmp = F.get(ch.upper()) or F[' ']
        if ch != ' ' and not any('1' in r for r in bmp):
            missing.append(ch)
    for r in range(GH):
        rows.append(sum(1 << (GW - 1 - c) for c in range(GW) if bmp[r][c] == '1'))

out = Path(__file__).with_name("font57.h")
with out.open("w") as f:
    f.write("/* generated by fly/gen_font.py from viz/font5x7w + punctuation - do not edit */\n")
    f.write("#ifndef FONT57_H\n#define FONT57_H\n")
    f.write("#define F57_LO %d\n#define F57_HI %d\n" % (LO, HI))
    f.write("#define F57_W %d\n#define F57_H %d\n" % (GW, GH))
    f.write("static const unsigned char FONT57[%d] = {\n" % len(rows))
    for i in range(0, len(rows), GH):
        f.write("    " + ",".join("0x%02x" % b for b in rows[i:i + GH]) + ",\n")
    f.write("};\n#endif\n")
print("wrote %s (%d glyphs)" % (out, HI - LO + 1))
if missing:
    print("still blank:", "".join(missing))
