#!/usr/bin/env python3
"""gen_font640.py - hinted bitmap fonts for IIgs 640-mode text rows.

FreeType renders each glyph in mono mode at its real pixel size, so the
hinter snaps stems and curves to the grid (the classic crisp small-font
look). The GS draws every source column as two 640 pixels, which on the
IIgs's tall 640 pixel gives roughly square proportions.

  FM  SF Mono 9 px       boot console (leaders and the bar line up)
  FP  Helvetica Neue 9   viewer chrome (proportional)

Header per font: <TAG>_ROWS, <TAG>_ADV[95] (source px; GS doubles it),
<TAG>_FULL[95*ROWS] 16-bit row masks, bit 15 = leftmost source column,
<TAG>_MID all zero (kept for the struct).
"""
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent

# tag, path, index, variation, pixel size, fallback
# Geneva 9 and Monaco 9: the original Mac screen fonts, hinted for exactly
# this size. Helvetica Neue and SF Mono fall apart in mono rendering at 9px.
FONTS = [
    ("FM", "/System/Library/Fonts/Monaco.ttf", 0, None, 9, "/System/Library/Fonts/Menlo.ttc"),
    ("FP", "/System/Library/Fonts/Geneva.ttf", 0, None, 9, "/System/Library/Fonts/LucidaGrande.ttc"),
]


def load(path, index, variation, size, fallback):
    try:
        f = ImageFont.truetype(path, size, index=index)
        if variation:
            f.set_variation_by_name(variation)
        return f
    except OSError:
        return ImageFont.truetype(fallback, size, index=0)


def glyph(font, ch):
    im = Image.new("1", (24, 20), 0)
    d = ImageDraw.Draw(im)
    d.fontmode = "1"
    d.text((0, 0), ch, font=font, fill=1)
    a = np.asarray(im).astype(np.uint8)
    adv = max(1, int(round(font.getlength(ch))))
    return adv, a


def emit(f, tag, font):
    glyphs = [glyph(font, chr(c)) for c in range(32, 127)]
    # cap top from H, descender bottom from g/p/y; brackets and | may
    # poke a row past either end and get clipped, which is fine
    alnum = [c for c in range(48, 123) if chr(c).isalnum()]
    top = min(int(np.nonzero(glyphs[c - 32][1].any(axis=1))[0].min()) for c in alnum)
    bot = max(int(np.nonzero(glyphs[c - 32][1].any(axis=1))[0].max()) for c in alnum)
    rows = int(bot - top + 1)
    advs, masks = [], []
    for adv, a in glyphs:
        advs.append(adv)
        for r in range(rows):
            m = 0
            row = a[top + r]
            for c in range(min(16, a.shape[1])):
                if row[c]:
                    m |= 1 << (15 - c)
            masks.append(m)
    f.write("/* %s: %s %s %dpx, %d rows */\n" % (tag, font.getname()[0], font.getname()[1], font.size, rows))
    f.write("#define %s_ROWS %d\n" % (tag, rows))
    f.write("static const unsigned char %s_ADV[95] = {\n    %s\n};\n" % (tag, ",".join(str(a) for a in advs)))
    f.write("static const unsigned %s_FULL[%d] = {\n" % (tag, len(masks)))
    for i in range(0, len(masks), rows):
        f.write("    " + ",".join("0x%04x" % v for v in masks[i:i + rows]) + ",\n")
    f.write("};\n")
    f.write("static const unsigned %s_MID[%d] = { 0 };\n" % (tag, len(masks)))
    print(tag, font.getname(), font.size, "px ->", rows, "rows, adv", min(advs), "-", max(advs),
          "(x2 on the GS)")


def main():
    out = HERE / "font640.h"
    with out.open("w") as f:
        f.write("/* generated by fly/gen_font640.py - do not edit */\n")
        f.write("#ifndef FONT640_H\n#define FONT640_H\n")
        for tag, path, index, variation, size, fallback in FONTS:
            emit(f, tag, load(path, index, variation, size, fallback))
        f.write("#endif\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
